import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import {SiGooglescholar} from 'react-icons/si';
import {GiCommercialAirplane} from 'react-icons/gi'
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/profile_pic.png";
import Image from "next/image";
import Link from "next/link";
import {Navbar} from "../components/navbar";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Daniel Lobo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <Navbar />
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Daniel Lobo
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Computer scientist.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Master's student at the University of Florida working on cybersecurity research.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a target="_blank" href="https://scholar.google.com/citations?user=2J9L7_EAAAAJ&hl=en">
                <SiGooglescholar />
              </a>
              <a target="_blank" href="https://www.linkedin.com/in/daniel-m-lobo/">
                <AiFillLinkedin />
              </a>
              <Link href='travels'>
                <GiCommercialAirplane />
              </Link>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image alt="My profile picture" src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}