import Head from "next/head"
import {Navbar} from "../components/navbar"
import { useState } from "react";

export default function Travels(){
    const [darkMode, setDarkMode] = useState(false);
    return (
        <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Daniel Lobo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
          <section className="min-h-screen">
            <Navbar />
          </section>
          <section>
            <div>
                
            </div>
          </section>
        </main>
      </div>
    );
}